FROM node:17.2-alpine

RUN mkdir -p /home/app
COPY . /home/app
WORKDIR /home/app

RUN apk update
RUN apk add --update apk-cron
RUN apk add jq curl

RUN chmod +x entry.prod.sh
RUN chmod +x config/run.sh
RUN /usr/bin/crontab config/crontab.txt

ENV NODE_OPTIONS --openssl-legacy-provider
ENV NUXT_BASE_API_URL https://api.leaf-valley.com/api
ENV HOST 0.0.0.0
ENV NUXT_HOST 0.0.0.0
RUN npm install
RUN npm run build


ENTRYPOINT ["/home/app/entry.prod.sh"]
