FROM node:17.2-alpine

RUN mkdir -p /home/app
COPY . /home/app
WORKDIR /home/app

ENV NODE_OPTIONS --openssl-legacy-provider
ENV NUXT_BASE_API_URL https://api-leaf-valley.herokuapp.com/api
ENV HOST 0.0.0.0
ENV NUXT_HOST 0.0.0.0
RUN npm install
RUN npm run build

CMD ["npm", "start"]
