FROM python:3.8.12-alpine

RUN mkdir -p /home/api
COPY . /home/api
WORKDIR /home/api

RUN apk update -y
RUN pip install -U --upgrade pip
RUN pip install -r /home/api/requirements.txt
ENV FLASK_ENV prod

CMD ["gunicorn", "main:app"]
