FROM python:3.8.12-slim-buster

RUN mkdir -p /home/api
COPY . /home/api
WORKDIR /home/api

RUN apt get update -y
RUN apt get install python3-opencv -y
RUN apt install libgl1-mesa-glx -y
RUN pip install -U --upgrade pip
RUN pip install -r /home/api/requirements.txt
ENV FLASK_ENV prod

CMD ["gunicorn", "main:app"]
