FROM golang:1.18-alpine

RUN mkdir -p /app

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./

RUN touch last_starting_cluster.txt
RUN go build -o /econome

EXPOSE 80

CMD [ "/econome" ]
