FROM golang:1.18-alpine

RUN mkdir -p /app

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./

# Access to render deployment .env file
COPY /etc/secrets/.env .

RUN ls -al
RUN go build -o /econome

EXPOSE 80

CMD [ "/econome" ]
