name: Eslint checker

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Go to client app directory
        run: cd app/client

      - name: Install dependecies
        run: npm ci

      - name: Run ESLint
        run: npm run lint