name: Deploy api to scaleway.

# Run workflow on every push to master branch.
on: ['push']

# Your workflows jobs.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      # We need to do that because docker build can't copy parent directory inside a docker.
      - name: Copy utilities in api folder
        run: cp -r utilities app/api/

      - name: Copy process in api folder
        run: cp -r process app/api/
      
      - name: Login to scaleway
        run: docker login rg.fr-par.scw.cloud/leaf-api -u nologin --password-stdin <<< ${{ secrets.SCW_SECRET_KEY }}

      - name: Docker build
        run: docker build -t leaf_api:latest -f app/api/Dockerfile.prod app/api

      - name: Docker tag
        run: docker tag leaf_api:latest rg.fr-par.scw.cloud/leaf-api/leaf_api:latest

      - name: Docker push in namespace
        run: docker push rg.fr-par.scw.cloud/leaf-api/leaf_api:latest

      - name: Create config file.
        run: mkdir -p $HOME/.config/ && echo ${{ secrets.SCW_CONFIG_FILE }} > $HOME/.config/scw

      - name: Run command cli
        run: docker run -it --rm -v $HOME/.config/scw:/root/.config/scw scaleway/cli:v2.5.4 container container deploy ${{ secrets.SCW_CONTAINER_ID }}
      
      - name: Remove utilities and process in api folder
        run: rm -rf app/api/utilities app/api/process $HOME/.config/