name: Deploy api to scaleway.

# Run workflow on every push to master branch.
on: ['push']

# Your workflows jobs.
jobs:
  deploy_scw:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      # We need to do that because docker build can't copy parent directory inside a docker.
      - name: Copy utilities in api folder
        run: cp -r utilities app/api/

      - name: Copy process in api folder
        run: cp -r process app/api/
      
      - name: Login to scaleway
        run: docker login rg.fr-par.scw.cloud/leaf-api -u nologin --password-stdin <<< ${{ secrets.SCW_SECRET_KEY }}

      - name: Docker build
        run: cd app/api && docker build -t leaf_api:latest -f Dockerfile.prod .

      - name: Docker tag
        run: docker tag leaf_api:latest rg.fr-par.scw.cloud/leaf-api/leaf_api:latest

      - name: Docker push in namespace
        run: docker push rg.fr-par.scw.cloud/leaf-api/leaf_api:latest

      - name: Create secret
        run: kubectl create secret docker-registry registry-secret --docker-server=rg.fr-par.scw.cloud --docker-username=leaf-api --docker-password=${{ secrets.SCW_SECRET_KEY }}

      - name: Apply deployment.yaml
        run: kubectl apply -f app/api/deployment.yaml

      - name: Delete previous svc
        run: kubectl delete svc  leafapideploy

      - name: Expose port 80
        run: kubectl expose deployment leafapideploy --type NodePort --port 80